# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wcate',
            name='wcate_people',
            field=models.TextField(default='', verbose_name='负责人介绍'),
        ),
    ]
